AWSTemplateFormatVersion: 2010-09-09
Description: >-
  tasker-back-end
Transform:
- AWS::Serverless-2016-10-31

Globals:
  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
    Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !GetAtt MyCognitoUserPool.Arn


Resources:
  lambdaHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: Lambda Function to interact with Dynamo DB
      Policies:
        # Give Create/Read/Update/Delete Permissions to the Tasker Table
        - DynamoDBCrudPolicy:
            TableName: TaskerTable
      Environment:
        Variables:
          # Make table and index name accessible as environment variable from function code during execution
          TABLE_NAME: TaskerTable
          GSI1_NAME: GetListTasks_GSI1
          GSI2_NAME: GetAllTasks_GSI2
      Events:
        Api:
          Type: Api
          Properties:
            Path: /users/{userId}/items
            Method: ANY

  MyCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref CognitoUserPoolName
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  
  MyCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref MyCognitoUserPool
      ClientName: !Ref CognitoUserPoolClientName
      GenerateSecret: false

  # DynamoDB table to store items
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TaskerTable
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: CreatedBy
          AttributeType: S
        - AttributeName: TaskArchive
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: GetListTasks_GSI1
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
        - IndexName: GetAllTasks_GSI2
          KeySchema:
            - AttributeName: CreatedBy
              KeyType: HASH
            - AttributeName: TaskArchive
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2


Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"