AWSTemplateFormatVersion: 2010-09-09
Description: >-
  tasker-back-end
Transform:
- AWS::Serverless-2016-10-31

Resources:
  lambdaHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: Lambda Function to interact with Dynamo DB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TaskerTable
      Environment:
        Variables:
          TABLE_NAME: TaskerTable
          GSI1_NAME: GetListTasks_GSI1
          GSI2_NAME: GetAllTasks_GSI2
      Events:
        Api:
          Type: Api
          Properties:
            Path: /users/{userId}/items
            Method: ANY

  TaskerUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: TaskerUserPool
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  
  TaskerUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref TaskerUserPool
      ClientName: TaskerUserPoolClient
      GenerateSecret: false
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs: 
        - http://localhost:4200
      LogoutURLs: 
        - http://localhost:4200
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: taskerdomain
      UserPoolId: !Ref TaskerUserPool

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TaskerTable
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: CreatedBy
          AttributeType: S
        - AttributeName: TaskArchive
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      GlobalSecondaryIndexes:
        - IndexName: GetListTasks_GSI1
          KeySchema:
            - AttributeName: SK
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
        - IndexName: GetAllTasks_GSI2
          KeySchema:
            - AttributeName: CreatedBy
              KeyType: HASH
            - AttributeName: TaskArchive
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2


Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"